version: '3'

services:
  app:
    build:
      context: ./docker/php
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    environment:
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-serverName=docker}
    volumes:
      - ./:/app:cached
  nginx:
    image: nginx:1.26-alpine
    volumes:
      - ./:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
    depends_on:
      - app
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: