<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240623081146 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Добавлена таблица для уведомлений';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text VARCHAR(255) NOT NULL, link VARCHAR(255) DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $adminUserId = $this->connection->fetchOne("SELECT id FROM \"user\" WHERE username = 'admin'");
        $scheduleIds = $this->connection->fetchAllAssociative("SELECT id FROM temp_schedule ORDER BY id DESC LIMIT 3");
        $this->addSql("INSERT INTO notification (text, link, date, is_read, user_id) VALUES ('Сгенерирован график на 01-2024', ?, '2024-06-17 00:00:00', false, ?)", [$scheduleIds[0]['id'] ?? null, $adminUserId]);
        $this->addSql("INSERT INTO notification (text, link, date, is_read, user_id) VALUES ('Сгенерирован график на 01-2024', ?, '2024-06-21 00:00:00', false, ?)", [$scheduleIds[1]['id'] ?? null, $adminUserId]);
        $this->addSql("INSERT INTO notification (text, link, date, is_read, user_id) VALUES ('Сгенерирован график на 01-2024', ?, '2024-06-21 00:00:00', false, ?)", [$scheduleIds[2]['id'] ?? null, $adminUserId]);

    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('DROP TABLE notification');
    }
}
