<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Enum\StudyType;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240610212039 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Добавление таблицы для хранения предсказанных данных';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE week_studies_predicted (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, week_number INT NOT NULL, year INT NOT NULL, count INT NOT NULL, is_new BOOLEAN DEFAULT true NOT NULL, competency_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DC2D2C6FB9F58C ON week_studies_predicted (competency_id)');
        $this->addSql('ALTER TABLE week_studies_predicted ADD CONSTRAINT FK_DC2D2C6FB9F58C FOREIGN KEY (competency_id) REFERENCES competencies (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE competencies ADD code VARCHAR(255) DEFAULT NULL');
        $this->addSql('COMMENT ON COLUMN competencies.code IS \'Код\'');
        $this->addSql('ALTER TABLE week_studies ADD is_new BOOLEAN DEFAULT true NOT NULL');

        foreach (StudyType::cases() as $type) {
            $code = $type->value;
            $label = $type->label();
            $this->addSql("UPDATE competencies SET code = '$code' WHERE modality = '$label'");
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE week_studies_predicted DROP CONSTRAINT FK_DC2D2C6FB9F58C');
        $this->addSql('DROP TABLE week_studies_predicted');
        $this->addSql('ALTER TABLE competencies DROP code');
        $this->addSql('ALTER TABLE week_studies DROP is_new');
    }
}
